### ISSUE TITLE
Define Token Request error responses

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/known-customer-credential#17]
Originally ideated upon here https://github.com/TBD54566975/known-customer-credential/pull/12

We need to support all of the standard OAuth error responses https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2.1

As well as a few custom to OID4VCI https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-token-error-response

**_Specifically_** we need to add support to `authorization_pending` which will be returned in the event the IDV case is pending status

**Comment by tomdaffurn** [comment]
`authorization_pending` has been removed from OID4VCI, but other codes must be defined
