### ISSUE TITLE
Add JSON Schema for Known Customer Credential

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/known-customer-credential#21]

**Comment by nitro-neal** [comment]
related kt issue - https://github.com/TBD54566975/web5-kt/issues/114

**Comment by nitro-neal** [comment]
js pr - https://github.com/TBD54566975/web5-js/pull/491/files

**Comment by nitro-neal** [comment]
web5-kt - https://github.com/TBD54566975/web5-kt/pull/301

**Comment by nitro-neal** [comment]
Merged in known-customer-credential repo
