### ISSUE TITLE
Should `subject_syntax_types_supported` be an array of strings?

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/known-customer-credential#28]
## Context

The current KCC doc includes the following:

https://github.com/TBD54566975/known-customer-credential/blob/eabbb0df542d952cbbf41fc09c7f05c9aff8190a/README.md?plain=1#L290

which defines `subject_syntax_types_supported` as a "Space separated list of DID methods."

The [linked SIOPv2 spec](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#section-7.5-2.1.1) states:

> - subject_syntax_types_supported
>   - REQUIRED. A JSON array of strings representing URI scheme identifiers and optionally method names of supported Subject Syntax Types defined in [Section 8](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#sub-syntax-type). When Subject Syntax Type is JWK Thumbprint, a valid value is urn:ietf:params:oauth:jwk-thumbprint defined in [[RFC9278](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#RFC9278)]. When Subject Syntax Type is Decentralized Identifier, valid values MUST be a did: prefix followed by a supported DID method without a : suffix. For example, support for the DID method with a method-name "example" would be represented by did:example. Support for all DID methods is indicated by sending did without any method-name.

## Proposal

Change the `subject_syntax_types_supported` to be an array of strings.

## Additional Supporting Material

A variety of examples in the SIOPv2 spec such as:

```json
{
  "subject_syntax_types_supported": [
    "urn:ietf:params:oauth:jwk-thumbprint",
    "did:example",
    "did:key"
  ]
}
```

The use of an array of strings seems to be consistently implemented by other organizations / libraries:

#### [EBSI Conformance - Authorisation Server discovery metadata](https://hub.ebsi.eu/apis/conformance/conformance/v3/get-openid-configuration)

<details>
  <summary>Screenshot</summary>
  <div align="center">

  ![img](https://github.com/TBD54566975/known-customer-credential/assets/134693/7ba427be-06c9-42af-bfdd-af50df35ed6b)

  </div>
</details>

#### [EBSI Conformance Guide - Example](https://hub.ebsi.eu/conformance/learn/discovery-metadata#authorisation-server-metadata)

```json
{
  "issuer": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock",
  "authorization_endpoint": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock/authorize",
  "token_endpoint": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock/token",
  "jwks_uri": "https://api-conformance.ebsi.eu/conformance/v3/auth-mock/jwks",
  "scopes_supported": ["openid"],
  "response_types_supported": ["code", "vp_token", "id_token"],
  "response_modes_supported": ["query"],
  "grant_types_supported": ["authorization_code"],
  "subject_types_supported": ["public"],
  "id_token_signing_alg_values_supported": ["ES256"],
  "request_object_signing_alg_values_supported": ["ES256"],
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "token_endpoint_auth_methods_supported": ["private_key_jwt"],
  "vp_formats_supported": {
    "jwt_vp": {
      "alg_values_supported": ["ES256"]
    },
    "jwt_vc": {
      "alg_values_supported": ["ES256"]
    }
  },
  "subject_syntax_types_supported": ["did:key", "did:ebsi"],
  "subject_trust_frameworks_supported": ["ebsi"],
  "id_token_types_supported": [
    "subject_signed_id_token",
    "attester_signed_id_token"
  ]
}
```

#### [Microsoft Entra Wallet Library](https://github.com/microsoft/entra-verifiedid-wallet-library-android)

[Code excerpt](https://github.com/microsoft/entra-verifiedid-wallet-library-android/blob/cf79f69c2a21e7856256e8d70f384a62663e8e87/walletlibrary/src/main/java/com/microsoft/walletlibrary/did/sdk/credential/service/models/oidc/Registration.kt#L36-L37)

```kotlin
    @SerialName("subject_syntax_types_supported")
    val subjectSyntaxTypesSupported: List<String> = emptyList(),
```

#### [Open Wallet Foundation - Credo OpenID4VC Module](https://github.com/openwallet-foundation/credo-ts/tree/main/packages/openid4vc)

[Code excerpt](https://github.com/openwallet-foundation/credo-ts/blob/dcb363dc7e7abbbcce8b3a344a487a186eb5c88e/packages/openid4vc/src/openid4vc-verifier/OpenId4VcSiopVerifierService.ts#L441)

```ts
        subject_syntax_types_supported: supportedDidMethods.map((m) => `did:${m}`),
```

#### [Sphereon SIOP-OID4VP Library]()

- [Authorization Response schema](https://github.com/Sphereon-Opensource/SIOP-OID4VP/blob/b7ab7418ded18ce3219813f935f94192b31fd1e9/src/schemas/AuthorizationResponseOpts.schema.ts#L176-L181)
- [RP Registration Metadata schema](https://github.com/Sphereon-Opensource/SIOP-OID4VP/blob/b7ab7418ded18ce3219813f935f94192b31fd1e9/src/schemas/RPRegistrationMetadataPayload.schema.ts#L82-L86)

**Comment by decentralgabe** [comment]
I agree with supporting an array

**Comment by KendallWeihe** [comment]
Agreed with `subject_syntax_types_supported` being an array of strings, seems like a bug in our spec. @decentralgabe the SIOP spec appears correct, it's ours which is incorrect, or am I missing something?

**Comment by decentralgabe** [comment]
@KendallWeihe correct

**Comment by tomdaffurn** [comment]
Agree, it's a bug in this spec. We should fix
