### ISSUE TITLE
Host Schema URI

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/known-customer-credential#37]
### Reason

Currently we have the schema hosted [here ](https://purple-charming-snail-690.mypinata.cloud/ipfs/QmZbPpfPXsp4bFQvQvWRaexCu9Vxmj6qkwWerVfPwY9kQS) (for reference), we need to host it on our site. So that PFIs can actually use it when creating these credentials. 

- Thanks 💖

**Comment by frankhinek** [comment]
@EbonyLouis In progess: https://github.com/TBD54566975/schemas/issues/1

Hopefully we can have https://schemas.host online by the end of this week.

**Comment by tomdaffurn** [comment]
https://vc.schemas.host/kcc.schema.json is liiiiive. The contents will change - there are a number of fixes we need to make. But the URL should be stable now

**Comment by EbonyLouis** [comment]
yayyyy thanks!! @frankhinek @tomdaffurn
