### ISSUE TITLE
Add jurisdiction country to KCC schema

### ISSUE THREAD

**Issue by tomdaffurn** [TBD54566975/known-customer-credential#46]
Propose to add a `jurisdictionCountry` field to KCC schema to specify the legal jurisdiction where the issuer has performed IDV. 

jurisdictionCountry allows an issuer to:
- make a further claim about what IDV process they have use in issuing the KCC 
- constrain the usage of the KCC by jurisdiction, with a Presentation Definition filter. For example a product may offered in the US with a particular IDV requirement, and in Canada with a different IDV requirement.

```
"jurisdictionCountry":{
   "type":"string",
   "pattern":"^[A-Z]{2}$"
},
 ```

**Comment by decentralgabe** [comment]
is this guaranteed to be a single country?
could an issuer perform checks for a set of countries?

**Comment by tomdaffurn** [comment]
I think we should keep it as a single country for now. Other parts of the VC (e.g. evidence, checksPerformed, tier, expiry) make claims about the details of the IDV process, and it's unclear how to do that for multiple countries. Issuers have the option of minting a separate KCC for each country and managing expiry and data refresh separately.

**Comment by KendallWeihe** [comment]
Intuitively yeah this feels like a beneficial claim to add.

Is the proposal strictly for KCC, and not KBC? Or for both?

Will it be a required field within the `credentialSubject` or optional?

**Comment by decentralgabe** [comment]
@tomdaffurn makes sense to keep it at one.

Is country specific enough? I imagine, in the US, and other countries, certain states may have different specific jurisdictional requirements. 

It could make sense to make `jurisdiction` an object to allow for flexibility here. Alternatively, leave it as `jurisdiction` as a single string value, but make sure the values are as specific as necessary (could be a country, a state, providence, etc.).

**Comment by tomdaffurn** [comment]
> Is the proposal strictly for KCC, and not KBC? Or for both?

The current KBC schema is a minimal placeholder, so I don't see benefit adding jurisdictionCountry to it

**Comment by tomdaffurn** [comment]
I like the idea of leaving room for expansion with an object.
```
"jurisdiction": {
    "country": "<ISO 3166-1 alpha-2>",
}
```
3166-2 subdivision could be added later to that object.
